version: "3.8"
services:
  wg-easy:
    image: wgeasy
    command: npm run serve
    volumes:
      - ./src/:/app/
    environment: 
      - PASSWORD=/run/secrets/wireguard_password
      - WG_HOST=/run/secrets/wireguard_host
    secrets:
      - wireguard_password
      - wireguard_host
secrets:
  wireguard_password:
    external: true
  wireguard_host:
    external: true

# require docker swarm to test
# docker swarm int
# printf "password" | docker secret create wireguard_password -
# printf "domain.com" | docker secret create wireguard_host -
# docker stack deploy -c docker-compose.dev-secrets.yml wg-easy